version: '3.4'

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        UID_USER_SYSTEM: ${UID_USER_SYSTEM}
        USER_SYSTEM: ${USER_SYSTEM}
    stdin_open: true
    env_file: 
      - .env
    entrypoint: ./docker/entrypoint.sh
    container_name: umbler-challenge-backend
    networks:
      - umbler_challenge
    ports:
      - 9000:9000
    volumes:
      - type: bind
        source: .
        target: /usr/src/app
  mysql:
    image: mysql:5.7
    networks:
      - umbler_challenge
    volumes:
      - ./docker/init.sql:/data/application/init.sql
    command: --init-file /data/application/init.sql
    container_name: umbler_challenge_db
    environment:
      - MYSQL_DATABASE=umbler_challenge_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
networks:
  umbler_challenge:
    name: umbler_challenge_network
    driver: bridge